language: swift
osx_image: xcode10.1
xcode_project: Listy.xcodeproj

matrix:
  include:
    - xcode_scheme: "Listy iOS"
      xcode_sdk: iphonesimulator12.1

    - xcode_scheme: "Listy tvOS"
      xcode_sdk: appletvsimulator12.1

    - xcode_scheme: "ListyUI iOS"
      xcode_sdk: iphonesimulator12.1

    - xcode_scheme: "ListyKit iOS"
      xcode_sdk: iphonesimulator12.1

after_success:
  - bash <(curl -s https://codecov.io/bash)
